# Generated by Django 3.0.4 on 2020-03-08 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(db_column='in_id_departamento', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='vc_nombre', max_length=100)),
                ('description', models.CharField(blank=True, db_column='vc_description', max_length=500, null=True)),
            ],
            options={
                'db_table': 'departamento',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(db_column='in_id_provincia', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='vc_nombre', max_length=100)),
                ('description', models.CharField(blank=True, db_column='vc_description', max_length=500, null=True)),
                ('departamento', models.ForeignKey(db_column='in_id_departamento', on_delete=django.db.models.deletion.DO_NOTHING, to='api.Departamento')),
            ],
            options={
                'db_table': 'provincia',
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.AutoField(db_column='in_id_distrito', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='vc_nombre', max_length=100)),
                ('description', models.CharField(blank=True, db_column='vc_description', max_length=500, null=True)),
                ('provincia', models.ForeignKey(db_column='in_id_provincia', on_delete=django.db.models.deletion.DO_NOTHING, to='api.Provincia')),
            ],
            options={
                'db_table': 'distrito',
            },
        ),
    ]
